name: smartgraph
channels:
  - rdkit
  - conda-forge
  - defaults
dependencies:
  - networkx=2.5.1
  - pandas=1.1.5
  - pip=21.2.2
  - python=3.9.16
  - rdkit=2020.09.1.0
  - requests=2.27.1
  - pydantic=1.10.2
  - orjson=3.7.8
  - uvicorn=0.20.0
  - pip:
    - fastapi==0.83.0
    - neo4j==4.4.7

